version: "2"
services:
  app:
    container_name: client
    restart: always
    build:
      context: "client/"
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - "server"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - "server:server"
  
  server:
    container_name: server
    restart: always
    build:
      context: "server/"
      dockerfile: "Dockerfile"
    environment:
     - DB_HOST=mongodb
     - DB_USER=banker
     - DB_PASSWORD=password
     - DB_NAME=bankManager
    volumes:
      - ./server/src:/demo_project_server/src
    ports:
      - "8080:8080"

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
